name: Build and deploy Node.js app to Azure Web App - Nodejs-Appln

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        
    - name: 'Deploy Azure Web App'
      uses: azure/webapps-deploy@v1
      with:
       app-name: livedemoapp
       publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
